<?php
namespace Database\Seeders;
use App\Models\LocalLevel;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LocalLevelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $localLevels = [
            ['2086', 2008, 'Aathrai tirbeni Rural Municipaltiy', 'अठराई त्रिवेणी गाउँपालीका'],
            ['2087', 2008, 'Sidingwa  Rural Municipaltiy', 'सिदिङवा गाउँपालिका'],
            ['2088', 2008, 'Phaktanglung Rural Municipaltiy', 'फक्ताङलुङ गाउँपालिका'],
            ['2089', 2008, 'Mikwakhola Rural Municipaltiy', 'मिक्वाखोला गाउँपालिका'],
            ['2085', 2008, 'Fungling Municipality', 'फुङलिङ नगरपालिका'],
            ['2090', 2008, 'Meringden Rural Municipaltiy', 'मेिरङदेन गाउँपालिका'],
            ['2094', 2008, 'Shirijagha Rural Muncipality', 'सिरीजङा गाउँपालीका'],
            ['2091', 2008, 'MAIWAKHOLA RURAL MUNICIPALITY', 'मैवाखोला गाउँपालिका'],
            ['2092', 2008, 'Yankwarak Rural Municipaltiy', 'याङवरक गाउँपालिका'],

            ['2097', 2009, 'FALGUNANDA RURAL MUNICIPALITY', 'फाल्गुनन्द गाउँपालिका'],
            ['2093', 2009, 'Phidim Municipality', 'फिदिम नगरपालिका'],
            ['2101', 2009, 'Yangworak Rural Municipality', 'याङवरक गाउँपालिका'],
            ['2100', 2009, 'TUMBEWA RURAL MUNICIPALITY', 'तुम्बेबा गाँउपालिका'],
            ['2099', 2009, 'Miklagung Rural Municipality', 'मिक्लाजुङ गाउँपालिका'],
            ['2098', 2009, 'Kummayak Rural Municipality', 'कुम्मायक गाउँपालिका'],
            ['2096', 2009, 'Hilihang Rural Municipality', 'हिलिहाङ गाउँपालिका'],
            ['2095', 2009, 'Phalelung Rural Municipality', 'फालेलुङ गाउँपालिका'],

            ['2106', 2010, 'suryodaya Municipaltiy', 'सुर्योदय नगरपालिका'],
            ['2103', 2010, 'DEUMAI MUNICIPALITY', 'देउमाई नगरपालीका'],
            ['2105', 2010, 'Phakpohkthum Rural Municipaltiy', 'फाकफोकथुम गाउँपालिका'],
            ['2107', 2010, 'Chulachuli Rural Municipaltiy', 'चुलाचुली गाउँपालिका'],
            ['2108', 2010, 'Maeejogmai  Rural Municipaltiy', 'माईजोगमाई गाउँपालिका'],
            ['2109', 2010, 'Mangsebung Rural Municipaltiy', 'माङसेवुङ गाउँपालिका'],
            ['2110', 2010, 'Rong Rural Municipaltiy', 'रोङ गाउँपालिका'],
            ['2111', 2010, 'SANDAKPUR RURAL MUNICIPALITY', 'सन्दकपुर गाउँपालिका'],
            ['2104', 2010, 'Maee Municipality', 'माई नगरपालिका'],
            ['2102', 2010, 'Ilam  Municipaltiy', 'ईलाम नगरपालिका'],

            ['2196', 2011, 'Pachkhapan  Municipality', 'पाचँखपन नगरपालीका'],
            ['2190', 2011, 'Chainpur Municipality', 'चैनपुर नगरपालीका'],
            ['2192', 2011, 'Dharma Devi Municipality', 'धर्म देवि नगरपालीका'],
            ['2194', 2011, 'Khadbariu  Municipaltiy', 'खादँबारी नगरपालीका'],
            ['2195', 2011, 'Madi  Municipaltiy', 'मादी नगरपालीका'],
            ['2197', 2011, 'Bhotekhola Rural Municipaltiy', 'भोटेखोला गाउँपालिका'],
            ['2198', 2011, 'Chichila Rural Municipaltiy', 'चिचिला गाउँपालिका'],
            ['2200', 2011, 'Makalu Rural Municipality', 'मकालु गाउँपालिका'],
            ['2201', 2011, 'Shabhapokhari Rural Municipality', 'सभापोखरी गाउँपालिका'],
            ['2203', 2011, 'Silichong Rural Municipality', 'सिलीचोङ गाउँपालिका'],

            ['2189', 2012, 'MENCHHAYEM RURAL MUNICIPALITY', 'मेन्छयायेम गाउँपालिका'],
            ['2176', 2012, 'MYANGLUNG MUNICIPALITY', 'म्याङलुङ नगरपालीका'],
            ['2179', 2012, 'Laligurasa  Municipaltiy', 'लालीगुरास नगरपालीका'],
            ['2182', 2012, 'Aatharai Rural Municipaltiy', 'आठराई गाउँपालिका'],
            ['2185', 2012, 'Chathara Rural Municipaltiy', 'छथर गाउँपालिका'],
            ['2187', 2012, 'Fedapa Rural Municipaltiy', 'फेदाप गाउँपालिका'],
            ['2188', 2013, 'Chaubise Rural Municipality', 'चौबिसे गाउँपालिका'],

            ['2186', 2013, 'Chhathar Jorpati Rural Municipality', 'छथर जोरपाटी गाउँपालिका'],
            ['2164', 2013, 'Pakhirbas  Municipaltiy', 'पाख्र्रीबास नगरपालिका'],
            ['2169', 2013, 'Dhankuta Municipality', 'धनकुटा नगरपालीका'],
            ['2174', 2013, 'Mahalaxmi Municipality', 'महालक्ष्मी नगरपालीका'],
            ['2183', 2013, 'Khalsa Chintang Sahidbhumi Rural Municipality', 'खाल्सा छिन्ताङ सहिदभुमी'],
            ['2178', 2013, 'Saguragadhi Rural Municipality', 'सागुँरीगढी गाउँपालिका'],

            ['2212', 2014, 'AAMCHOK RURAL MUNICIPALITY', 'आमचोक गाउँपालिका'],
            ['2216', 2014, 'HATUBAGADHI RURAL MUNICIPALITY', 'हतुबागढी गाउँपालिका'],
            ['2211', 2014, 'SALPASILICHHO RURAL MUNICIPALITY', 'साल्पासिलिछो गाउँपालिका'],
            ['2207', 2014, 'Pauwadunma Rural Municipaltiy', 'पौबादुङमा गाउँपालिका'],
            ['2204', 2014, 'Arun Rural Municipaltiy', 'अरूण गाउँपालिका'],
            ['2202', 2014, 'RAMPRASAD DARAI RURAL MUNICIPALITY', 'रामप्रसादराई गाउँपालिका'],
            ['2199', 2014, 'TYAMKEMAIYUN RURAL MUNICIPALITY', 'टयाम्केमैयुन गाउँपालिका'],
            ['2193', 2014, 'SADHANANDA MUNICIPALITY', 'षडानन्द नगरपालीका'],
            ['2191', 2014, 'BHOJPUR MUNICIPALITY', 'भोजपुर नगरपालीका'],
            ['2247', 2015, 'Sakela Rural Municipaltiy', 'साकेला गाउँपालिका'],
            ['2227', 2015, 'Kopilasgadhi Rural Municipaltiy', 'कोपिलासगढी गाउँपालिका'],
            ['2226', 2015, 'Khothang Rural Municipality', 'खोटेहाङ गाउँपालिका'],
            ['2225', 2015, 'Jantedhunga Rural Municipality', 'जन्तेढुङगा गाउँपालिका'],
            ['2224', 2015, 'LamidadaRural Municipality', 'लामीडाडाँ गाउँपालिका'],
            ['2223', 2015, 'Yeselukhark', 'एेसेलुखर्क गाउँपालिका'],
            ['2266', 2015, 'Barahapokhari Rural Municipality', 'बराहपोखरी गाउँपालिका'],
            ['2221', 2015, 'Rupakot  majhugadhi Rural Municipaltiy', 'रूपाकोट मझुवागढी नगरपालीका'],
            ['2217', 2015, 'Halesitribachang Municipality', 'हलेसीतृवाचङ नगरपालीका'],
            ['2245', 2015, 'Dripung Rural Municipality', 'दि्रपुङ गाउँपालिका'],
            ['2215', 2016, 'Setang Rural Municipality', 'सेताङ गाउँपालिका'],
            ['2214', 2016, 'Likhu pike Rural Municipaltiy', 'लिखु पिके गाउँपालिका'],
            ['2210', 2016, 'Nechsalyan Rural Municipality', 'नेचसल्यान गाउँपालिका'],
            ['2206', 2016, 'Dudhakoshi Rural Municipality', 'दुधकोसी गाउँपालिका'],
            ['2213', 2016, 'Mahakulung Rural Municipality', 'महाकुलुङ गाउँपालिका'],
            ['2205', 2016, 'Solidudhkunda Municipality', 'सोलुदुधकुण्ड नगरपालीका'],
            ['2208', 2016, 'khumbu pasang lamu', 'खुम्बु पासाङल्हामु गाउँपालिका'],
            ['2209', 2016, 'Dudhkosika Rural Municipality', 'दुधकोशीका गाउँपालिका'],
            ['2222', 2017, 'Chisakhugadhi Rural Municipaltiy', 'चिशंखुगढी गाउँपालिका'],
            ['2246', 2017, 'manebhanjyan Rural Municipaltiy', 'मानेभन्ज्याङ गाउँपालिका'],
            ['2218', 2017, 'shidhicharana municipality', 'सिद्धिचरण नगरपालिका'],
            ['2219', 2017, 'KHIJUDEMBA RURAL MUNICIPALITY', 'खिजीदेम्वा गाउँपालिका'],
            ['2220', 2017, 'Champadebi  Rular Municipality', 'चम्पादेवी गाउँपालिका'],
            ['2265', 2017, 'SUNKOSHI RURAL MUNICIPALITY', 'सुनकोसी गाउँपालिका'],
            ['2249', 2017, 'LIKHU RURAL MUNICIPALITY', 'लिखु गाउँपालिका'],
            ['2248', 2017, 'MOLUNG Rural Municipaltiy', 'मोलुङ गाउँपालिका'],
            ['2275', 2018, 'Udayepurgadhi Rural Municipality', 'उदयपुरगढी गाउँपालिाका'],
            ['2281', 2018, 'Sunkoshi Rural Municipality', 'सुनकोशी  गाउँपालिका'],
            ['2276', 2018, 'Tapli Rural Municipality', 'ताप्ली गाउँपालिका'],
            ['2269', 2018, 'Chaudadhigadi Municipality', 'चौदण्डीगढी नगरपालिका'],
            ['2267', 2018, 'Katari Municipality', 'कटारी नगरपालिका'],
            ['2271', 2018, 'Triyuga Municipality', 'त्रियुगा नगरपालिका'],
            ['2272', 2018, 'Belaka Municipality', 'वेलका नगरपालिका'],
            ['2279', 2018, 'Raitamai Rural Municipality', 'रौतामाई गाउँपालिका'],
            ['2113', 2019, 'Kankai municipality', 'कन्काई नगरपालिका'],
            ['2117', 2019, 'shivasataxi municipality', 'शिबसताक्षी नगरपालिका'],
            ['2123', 2019, 'JHAPA RURAL MUNICIPALITY', 'झापा गाउँपालिका'],
            ['2122', 2019, 'BARADASHI RURAL MUNICIPALITY', 'बाह्रदशी गाउँपालिका'],
            ['2121', 2019, 'Gauri gunj rural municipality', 'गौरीगज गाउँपालिका'],
            ['2112', 2019, 'Mechinagar Municipality', 'मेचिनगर नगरपालिका'],
            ['2118', 2019, 'Gauradaha Municipality', 'गौरादह नगरपालिका'],
            ['2115', 2019, 'Bhadrapur municipality', 'भद्रपुर नगरपालिका'],
            ['2119', 2019, 'Kamal rural municipality', 'कमल गाउँपालिका'],
            ['2124', 2019, 'Buddhashanti Rural Municipality', 'बुद्धशान्ती गाउँपालिका'],
            ['2125', 2019, 'Haldibari Rural Municipality', 'हल्दीवारी गाउँपालिका'],
            ['2116', 2019, 'ARJUNDHARA MUNICIPALITY', 'अजुर्नधारा नगरपालीका'],
            ['2114', 2019, 'Damka Muncipality', 'दमक नगरपालीका'],
            ['2126', 2019, 'Kanachanakabal Rural municipality', 'कचनकबल गाउँपालिका'],
            ['2120', 2019, 'birtamoda municipality', 'बिर्तामोड नगरपालिका'],
            ['2140', 2020, 'Jahada Rural Municipaltiy', 'जहदा गाउँपालिका'],
            ['2138', 2020, 'GRAMTHAN RURAL MUNICIPALITY', 'ग्रामथान गाउँपालिका'],
            ['2127', 2020, 'Biratnagar SMC', 'विराटनगर महानगरपालिका'],
            ['2146', 2020, 'Katahari Rural Municipaltiy', 'कटहरी गाउँपालीका'],
            ['2129', 2020, 'Letang Municipality', 'लेटाङ नगरपालिका'],
            ['2132', 2020, 'Ratuwamai Municipality', 'रतुवामाई नगरपालिका'],
            ['2130', 2020, 'Rangali Muncipality', 'रगेली नगरपालिका'],
            ['2131', 2020, 'PATHARI SANISCHARE MUNICIPALITY', 'पथरी शनीश्ररे नगरपालिका'],
            ['2147', 2020, 'kerabari  Rural Municipaltiy', 'केराबारी गाउँपालिका'],
            ['2133', 2020, 'Urlabari Municipaltiy', 'उर्लावारी नगरपालिका'],
            ['2134', 2020, 'Sundarharicha Muncipality', 'सुन्दरहरैचा नगरपालिका'],
            ['2136', 2020, 'Budhiganga  Rural Municipaltiy', 'बुढीगँगा गाउँपालिका'],
            ['2135', 2020, 'SUNBARSI MUNICIPALITY', 'सुनर्बषी नगरपालिका'],
            ['2137', 2020, 'Dhanpalthan Rural Municipaity', 'धनपालथान गाउँपालिका'],
            ['2128', 2020, 'Belbari Municipality', 'बेलबारी  नगरपालिका'],
            ['2148', 2020, 'Miklagunj Rural Municipaltiy', 'मिक्लाजुङ गाउँपालिका'],
            ['2141', 2020, 'kanepokhari Rural Municipaltiy', 'कानेपोखरी गाउँपालिका'],
            ['2158', 2021, 'Debanganja Rural Municipality', 'देवानगन्ज गाउँपालिका'],
            ['2149', 2021, 'Dharan SMC', 'धरान उप-महानगरपालिका'],
            ['2171', 2021, 'HARINAGARA RURAL MUNICIPALITY', 'हरिनगरा गाउँपालिका'],
            ['2150', 2021, 'ITAHARI SMC', 'ईटहरी उप-महानगरपालिका'],
            ['2156', 2021, 'Baraha Municipaltiy', 'बराह नगरपालिका'],
            ['2159', 2021, 'KOSHI RURAL MUNICIPALITY', 'कोशी गाउँपालिका'],
            ['2162', 2021, 'Gadhi Rural Municipaltiy', 'गढी गाउँपालिका'],
            ['2165', 2021, 'Barju Rural Municipaltiy', 'बर्जु गाउँपालिका'],
            ['2168', 2021, 'BHOKRAHA RURAL MUNICIPALITY', 'भोक्राहा गाउँपालिका'],
            ['2155', 2021, 'Ramdhuni Municipality', 'रामधुनी नगरपालिका'],
            ['2153', 2021, 'DUHABI MUNICIPALITY', 'दुहबी नगरपालिका'],
            ['2152', 2021, 'Inaruwa Muncipality', 'ईनरूवा नगरपालिका'],
            ['2277', 2022, 'DAKNESRARI MUNICIPALITY', 'डाक्नेश्ररी नगरपालीका'],
            ['2274', 2022, 'kanchanrup  Municipaltiy', 'कन्चनरूप नगरपालीका'],
            ['2299', 2022, 'KRISHNA SABRAN RURAL MUNICIPALITY', 'कृष्णासबरन गाउँपालिका'],
            ['2306', 2022, 'SAPTAKHOSHI  MUNICIPALITY', 'सप्तकोसी नगरपालिका'],
            ['2284', 2022, 'KHADAK MUNICIPALITY', 'खडक नगरपालीका'],
            ['2305', 2022, 'Mahadewa Rural Municipaltiy', 'महादेवा गाउँपालिका'],
            ['2308', 2022, 'TIRAHUT RURAL MUNICIPALITY', 'तिरहुत गाउँपालिका'],
            ['2321', 2022, 'Bisnupur   Rural Municipaltiy', 'बिष्णुपुर गाउँपालिका'],
            ['2302', 2022, 'CHHITRAMASTA RURAL MUNICIPALITY', 'छित्रमस्ता गाउँपालिका'],
            ['2270', 2022, 'Rajbiraj', 'राजबिराज नगरपालीका'],
            ['2313', 2022, 'Rupani Rural Municipaltiy', 'रूपनी गाउँपालिका'],
            ['2351', 2022, 'SHAHIDNAGAR MUNICIPALITY', 'शहीदनगर नगरपालीका'],
            ['2286', 2022, 'SHAMBHUNATH MUNICIPALITY', 'शम्भुनाथ नगरपालीका'],
            ['2294', 2022, 'HANUMANNAGAR KANKALINY MUNICIPALITY', 'हनुमाननगर कङकालिनी'],
            ['2316', 2022, 'BELHI CHAMENA RURAL MUNICIPALITY', 'बेल्ही चमेना गाउँपालिका'],
            ['2311', 2022, 'TILATHI KOIDI RURAL MUNICIPALITY', 'तिलाठी कोईलाडी गाउँपालिका'],
            ['2393', 2022, 'AURAHI RURAL MUNICIPALITY', 'औरही गाउँपालिका'],
            ['2290', 2022, 'Shurugha Municipaltiy', 'सुरूङगा नगरपालीका'],
            ['2282', 2022, 'BODEBARSAIN MUNICIPALITY', 'बोदेबरसाईन नगरपालीका'],
            ['2307', 2023, 'Mirchaya Municipality', 'मिर्चैया नगरपालीका'],
            ['2326', 2023, 'Bariyarpatti Rural Municipality', 'वरियारपटी गाउँपालिका'],
            ['2297', 2023, 'Lahan Municipality', 'लहान नगरपालीका'],
            ['2331', 2023, 'Laxmipur Patari Rural Municipality', 'लक्ष्मीपुर पतारी गाउँपालिका'],
            ['2309', 2023, 'Kalyanpur Municipality', 'कल्याणपुर नगरपालीका'],
            ['2310', 2023, 'Bhagwanpur Rural Municipaltiy', 'भगवानपुर गाउँपालिका'],
            ['2343', 2023, 'Sakhunankarakatti Rural Municipality', 'सखुवानान्कारकटी'],
            ['2312', 2023, 'Aurahi Rural Municipality', 'औरही गाउँपालिका'],
            ['2346', 2023, 'Arnama Rural Municipality', 'अर्नमा गाउँपालिका'],
            ['2315', 2023, 'Bishnupur Rural Municipality', 'विष्णुपुर गाउँपालिका'],
            ['2335', 2023, 'Naraha Rural Municipality', 'नरहा गाउँपालिका'],
            ['2322', 2023, 'kanjarh Rural Municipaltiy', 'कजनर््हा गाउँपालिका'],
            ['2349', 2023, 'Nawaorajpur Rural Municipality', 'नवराजपुर गाउँपालिका'],
            ['2304', 2023, 'Golbazer Municipaltiy', 'गोलबजार नगरपालीका'],
            ['2303', 2023, 'Siraha Municipality', 'सिरहा नगरपालीका'],
            ['2300', 2023, 'Dhangadimai Municipality', 'धनगढीमाई नगरपालीका'],
            ['2320', 2023, 'Sukhipur Municipaltiy', 'सुखीपुर नगरपालिका'],
            ['2357', 2024, 'KAMALA SHIDDHIDATRI RURAL MUNICIPALITY', 'कमला सिद्धीदात्री'],
            ['2368', 2024, 'MITHILA BIHARI RURAL MUNICIPALITY', 'मिथिला बिहारी गाउँपालिका'],
            ['2333', 2024, 'Chiresanata Rural Municipaltiy', 'क्ष्क्षिरेश्ररनाथ नगरपालीका'],
            ['2344', 2024, 'Bideha  Municipaltiy', 'बिदेह नगरपालीका'],
            ['2390', 2024, 'Hansapur Rural Municipaltiy', 'हंसपुर गाउँपालिका'],
            ['2328', 2024, 'JANAKPUR SMC', 'जनकपुर उपमहानगरपालिका'],
            ['2348', 2024, 'Mithila  Municipaltiy', 'मिथिला नगरपालीका'],
            ['2341', 2024, 'NAGARAIN MUNICIPALITY', 'नगराइन नगरपालीका'],
            ['2339', 2024, 'DHANUSATHAM MUNICIPALITY', 'धनुषाथाम नगरपालीका'],
            ['2387', 2024, 'Laxminiya Rural Municipaltiy', 'लक्ष्मीनिया गाउँपालिका'],
            ['2336', 2024, 'GANESHMAN CHARNATA MUNICIPALITY', 'गणेशमान चारनाथ नगरपालीका'],
            ['2364', 2024, 'BATESRAR RURAL MUNICIPALITY', 'बट्टेश्वर गाउँपालिका'],
            ['2373', 2024, 'MUKHIYAPATI MUSHAHARMIYA RURAL MUNICIPALITY', 'मुखियापटी मुसहरमिया गाउँपालिका'],
            ['2354', 2024, 'SABAILA MUNICIPALITY', 'सबैला नगरपालीका'],
            ['2361', 2024, 'Jankanadine Rural Municipaltiy', 'जनकनन्दिनी गाउँपालिका'],
            ['2371', 2025, 'Ramgopalpur Municipality', 'रामगोपालपुर नगरपालिका'],
            ['2386', 2025, 'Bhangaha Municipality', 'भँगाहा नगरपालिका'],
            ['2367', 2025, 'Sanema Rural Municipaltiy', 'सानेमा गाउँपालिका'],
            ['2363', 2025, 'Yekdara Rural Municipality', 'एकडारा गाउँपालिका'],
            ['2359', 2025, 'Gaushala Municipality', 'गौशाला नगरपालीका'],
            ['2353', 2025, 'Jaleshwor Municipaltiy', 'जलेश्वर नगरपालीका'],
            ['2391', 2025, 'Pipara Rural Municipality', 'पिपरा गाउँपालिका'],
            ['2370', 2025, 'Loharpatti Municipaltiy', 'लोहरपटी नगरपालिका'],
            ['2372', 2025, 'Mahottari Rural Municipality', 'महोत्तरी गाउँपालिका'],
            ['2375', 2025, 'Matihani Municipaltiy', 'मटिहानी नगरपालिका'],
            ['2356', 2025, 'Bardibas  Municipaltiy', 'बर्दिबास नगरपालिका'],
            ['2369', 2025, 'Samsi Rural Municipality', 'साम्सी गाउँपालिका'],
            ['2395', 2025, 'Aaurahi Municipality', 'औरही नगरपालिका'],
            ['2374', 2025, 'Manara Shisawa Municipaltiy', 'मनरा शिसवा नगरपालिका'],
            ['2389', 2025, 'Balawa Municipality', 'बलवा नगरपालिका'],
            ['2429', 2026, 'ChandraNagar Rural Municipality', 'चन्द्रनगर गाउँपालिका'],
            ['2430', 2026, 'Dhankoul Rural Municipality', 'धनकौल गाउँपालिका'],
            ['2483', 2026, '
            Parsa Rural Municipality', 'पर्सा गाउँपालिका'],
            ['2434', 2026, 'Brahapuri Rural Municipaltiy', 'ब्रहापुरी गाउँपालिका'],
            ['2437', 2026, 'Ramnagar Rural Municipaltiy', 'रामनगर  गाउँपालिका'],
            ['2410', 2026, 'Hariwan Municipality', 'हरिवन नगरपालिका'],
            ['2411', 2026, 'Barahthawa Municipality', 'बरहथवा नगरपालिका'],
            ['2415', 2026, 'Balara  Municipaltiy', 'बलरा नगरपालिका'],
            ['2417', 2026, 'Godaita  Municipaltiy', 'गोडैटा नगरपालिका'],
            ['2418', 2026, 'Bagmati Municipality', 'बागमती नगरपालिका'],
            ['2408', 2026, 'Haripurba Municipality', 'हरिपुर्वा नगरपालिका'],
            ['2404', 2026, 'Lalbandi  Municipaltiy', 'लालबन्दी नगरपालिका'],
            ['2482', 2026, 'Kodena Rural Municipality', 'कोडैना गाउँपालिका'],
            ['2481', 2026, '
            Basbariya Rural Municipality', 'बसबरिया गाउँपालिका'],
            ['2406', 2026, 'Haripur  Municipaltiy', 'हरीपुर नगरपालिका'],
            ['2422', 2026, 'Kabilasi Rural Municipaltiy', 'कविलासी गाउँपालिका'],
            ['2399', 2026, 'Malangwa Municipality', 'मलंगवा नगरपालिका'],
            ['2397', 2026, 'Ishworpur Municipality', 'इश्वरपुर नगरपालिका'],
            ['2426', 2026, 'Chakraghatta Rural Municipality', 'चक्रघटा गाउँपालिका'],
            ['2439', 2026, 'Bishnu Rural Municipality', 'विष्णु  गाउँपालिका'],
            ['2734', 2027, 'Debahi Gonahi Rular Muncipality', 'देवाही गोनाही गाउँपालीका'],
            ['2752', 2027, 'Rajapur Rular Muncipality', 'राजापुर गाउँपालिका'],
            ['2750', 2027, 'Paroha Rular Muncipality', 'परोहा गाउँपालिका'],
            ['2748', 2027, 'Ishnath Rular Muncipality', 'ईसनाथ गाउँपालिका'],
            ['2747', 2027, 'Phatuwabijyapur Rular Muncipality', 'फतुवाविजउपुर गाउँपालिका'],
            ['2746', 2027, 'Maulapur Rular Muncipality', 'मौलापुर गाउँपालिका'],
            ['2744', 2027, 'Madhav Naryana Rular Muncipality', 'माधव नारायण गाउँपालिका'],
            ['2742', 2027, 'Katahariya Rular Muncipality', 'कटहरीया गाउँपालिका'],
            ['2740', 2027, 'Gajura Rular Muncipality', 'गँजुरा गाउँपालिका'],
            ['2739', 2027, 'Gadhimai Rular Muncipality', 'गढीमाई गाउँपालिका'],
            ['2737', 2027, 'Durga bhanwoti Rular Muncipality', 'दुर्गा भगवती गाउँपालिका'],
            ['2730', 2027, 'Brindaban Rular Muncipality', 'बृदावन गाउँपालीका'],
            ['2728', 2027, 'Baudhimai Rular Muncipality', 'बौधीमाइ गाउँपालीका'],
            ['2725', 2027, 'Gaur Muncipality', 'गौर नगरपालीका'],
            ['2722', 2027, 'Garuda Muncipality', 'गरूडँा नगरपालीका'],
            ['2715', 2027, 'Chandrapur Muncipality', 'चन्द्रपुर नगरपालीका'],
            ['2795', 2028, 'Simmarngadha Muncipality', 'सिम्रौनगढ नगरपालिका'],
            ['2799', 2028, 'Karaiyamai Rural Muncipality', 'करैयामाई गाउँपालिका'],
            ['2797', 2028, 'Adarsha kotwal Rural Muncipality', 'आर्दश कोटवाल गाउँपालीका'],
            ['2792', 2028, 'Mahagadhimai Muncipality', 'महागढीमाई नगरपालीका'],
            ['2790', 2028, 'Nijgadha Muncipality', 'निजगढ नगरपालीका'],
            ['2787', 2028, 'Kohalbi Muncipality', 'कोहल्वी नगरपालीका'],
            ['2783', 2028, 'Jitpursimara Submetropolitiancity', 'जितपुरसिमारा उपमहानगरपालीका'],
            ['2776', 2028, 'Kalaiya submetropolitiancity', 'कलैया उपमहानगरपालीका'],
            ['2818', 2028, 'Parwanipur Rural Muncipality', 'परवानीपुर गाउँपालीका'],
            ['2821', 2028, 'Parsauni Rular Muncipality', 'प्रसौनी गाउँपालीका'],
            ['2824', 2028, 'Fetha Rular Muncipality', 'फेटा गाउँपालीका'],
            ['2826', 2028, 'Baragadhi Rural Muncipality', 'बारागढी गाउँपालीका'],
            ['2801', 2028, 'Debtal Rural Muncipality', 'देवताल गाउँपालीका'],
            ['2815', 2028, 'Pachrauta Municipality', 'पचरौता नगरपालिका'],
            ['2828', 2028, 'Suwarna Muncipality', 'सुवर्ण गाउँपालिका'],
            ['2889', 2029, 'Pokharia Muncipality', 'पोखरीया नगरपालीका'],
            ['2922', 2029, 'Paterwa sugauli Rural Muncipality', 'पटेर्वा सुगौली गाउँपालीका'],
            ['2919', 2029, 'Sakhuwa Parsauni Rural Muncipality', 'सखुवा प्रसौनी गाउँपालीका'],
            ['2917', 2029, 'Parsagadhi Muncipality', 'पर्सागढी गाउँपालीका'],
            ['2916', 2029, 'Belawa Rural Mumcipality', 'बेलवा गाउँपालीका'],
            ['2914', 2029, 'Bahudramai Rural Muncipality', 'बहुदरमाई गाउँपालीका'],
            ['2905', 2029, 'Bindbasini Rural Muncipality', 'बिन्दबासिनी गाउँपालीका'],
            ['2903', 2029, 'Pakaha Mainpur Rural Muncipality', 'पकाहा मैनपुर गाउँपालीका'],
            ['2900', 2029, 'Chipaharmai Rural Muncipality', 'छिपहरमाई गाउँपालीका'],
            ['2898', 2029, 'Dhobini Rural Muncipality', 'धोबिनी गाउँपालीका'],
            ['2897', 2029, 'Jagarnathpur Rural Muncipality', 'जगरनाथपुर गाउँपालीका'],
            ['2894', 2029, 'Suwornapur Rural Muncipality', 'सुवर्णपुर गाउँपालीका'],
            ['2875', 2029, 'Birgunj MetropolitanCity', 'वीरगंज महानगरपालिका'],
            ['2454', 2030, 'GAURISANKAR RURAL MUNICIPALITY', 'गौरिशंकर गाउँपालिका'],
            ['2468', 2030, 'SAILUNG RURAL MUNICIPALITY', 'शैलुङ गाउँपालिका'],
            ['2470', 2030, 'Melunga Rular Minicipality', 'मेलुङ गाउँपालिका'],
            ['2472', 2030, 'BAITESWAR RURAL MUNICIPALITY', 'वैतेश्रर गाउँपालीका'],
            ['2444', 2030, 'JIRI MUNICIPALITY', 'जिरी नगरपालिका'],
            ['2447', 2030, 'Bhimeshwar  Municipaltiy', 'भिमेश्रर नगरपालीका'],
            ['2450', 2030, 'kalinchowok Rural Municipaltiy', 'कालिन्चोक गाउँपालिका'],
            ['3074', 2030, 'Bigu Rular Minicipality', 'विगु गाउँपालिका'],
            ['2457', 2030, 'TAMAKOSHI RURAL MUNICIPALITY', 'तामाकोशी गाउँपालिका'],
            ['2758', 2030, 'Chumanubi Rular Municipality', 'चुमनुबी गाउँपालीका'],
            ['2449', 2031, 'Khadadevi Rural Municipality', 'खाडादेवि  गाउँपालिका'],
            ['2441', 2031, 'Manthali Municipality', 'मन्थली नगरपालीका'],
            ['2446', 2031, 'Umakunda Rural Municipality', 'उमाकुण्ड गाउँपालिका'],
            ['2443', 2031, 'Ramechhap Municipality', 'रामेछाप नगरपालीका'],
            ['2456', 2031, 'Doramba Rural Municipaltiy', 'दोरम्बा गाउँपालिका'],
            ['2458', 2031, 'LIKHU RURAL MUNICIPALITY', 'लिखु गाउँपालिका'],
            ['2459', 2031, 'SUNAPATI RURAL MUNICIPALITY', 'सुनापती गाउँपालिका'],
            ['2453', 2031, 'Gokul Ganga', 'गोकुलगङगा  गाउँपालिका'],
            ['2400', 2032, 'KAMALAMAI MUNICIPALITY', 'कमलामाई नगरपालीका'],
            ['2405', 2032, 'DUDHAULI MUNICIPALITY', 'दुधौली नगरपालीका'],
            ['2412', 2032, 'GOLANJOR RURAL MUNICIPALITY', 'गोलन्जोर गाउँपालिका'],
            ['2421', 2032, 'GHYANLEKHRURAL MUNICIPALITY', 'घ्याङलेख गाउँपालिका'],
            ['2425', 2032, 'Tinpatak', 'तिनपाटन गाउँपालिका'],
            ['2431', 2032, 'Fikkal Rural Municipaltiy', 'फिक्कल गाउँपालिका'],
            ['2433', 2032, 'MARIN RURAL MUNICIPALITY', 'मरिण गाउँपालिका'],
            ['2436', 2032, 'sunkoshi Rural Municipaltiy', 'सुनकोसी गाउँपालिका'],
            ['2440', 2032, 'HARIHARPURGADHI RURAL MUNICIPALITY', 'हरिहरपुरगढी गाउँपालिका'],
            ['2577', 2033, 'Roshi Rural Municipality', 'रोशी गाउँँपालिका'],
            ['2575', 2033, 'Mahavarat Rural Municipality', 'महाभारत गाउँपालिका'],
            ['2571', 2033, 'Mandandeupur Municipality', 'मण्डनदेउपुर नगरपालिका'],
            ['2548', 2033, 'Khanikhola Rural Municipality', 'खानीखोला गाउँपालिका'],
            ['2544', 2033, 'Pachakhal Municipality', 'पाँचखाल नगरपालिका'],
            ['2543', 2033, 'Panuati Municipality', 'पनौती नगरपालिका'],
            ['2542', 2033, 'Banepa Municipaity', 'बनेपा नगरपालिका'],
            ['2541', 2033, 'Dhulikhel Municipality', 'धुलिखेल नगरपालिका'],
            ['2546', 2033, 'Namabuddha  Municipality', 'नमोबुद्ध नगरपालिका'],
            ['2565', 2033, 'Chaurideaurali Rural Municipality', 'चौरीदेउराली गाउँपालिका'],
            ['2566', 2033, 'Temal Rular Municipality', 'तेमाल गाउँपालिका'],
            ['2567', 2033, 'Bethanchowok Rural Municipality', 'बेथानचोक गाउँपालिका'],
            ['2569', 2033, 'Bhumlu Rural Municipality', 'भुम्लु गाउँपालिका'],
            ['2508', 2034, 'Indrabati  Rural Municipality', 'ईन्द्राबती गाँउपालिका'],
            ['2505', 2034, 'Chautara Sangachowkgadi Municipality', 'चौतारा साँगाचोकगढी नगरपालिका'],
            ['2536', 2034, 'Tirpurasundari Rural Municipality', 'त्रिपुरासुन्दरी गाउँपालिका'],
            ['2533', 2034, 'Helambu Rular Municipality', 'हेलम्बु गाउँपालिका'],
            ['2531', 2034, 'Sunkoshi Rural Municipality', 'सुनकोशी गाउँपालिका'],
            ['2527', 2034, 'Lisakhu pakhar Rural Municipality', 'लिसंखु पाखर गाउँपालिका'],
            ['2522', 2034, 'Bhotekoshi Rural Municipality', 'भाटेकोशी गाउँपालिका'],
            ['2518', 2034, 'Balefi Rural Municipality', 'बलेफी गाउँपालिका'],
            ['2516', 2034, 'Pachapokhari Thanpal Rural Minicipality', 'पाँचपोखरी थाङपाल गाउँपालिका'],
            ['2514', 2034, 'Jugal Rural Minicipality', 'जुगल गाँउपालिका'],
            ['2507', 2034, 'Melamchi Municipality', 'मेलम्ची नगरपालिका'],
            ['2506', 2034, 'Barabise Municipality', 'बाह्रबिसे नगरपालिका'],
            ['2638', 2035, 'Naukundha Rular municipality', 'नौकुन्ड गाउँपालिका'],
            ['2635', 2035, 'Goshahikundha Rular municipality', 'गोसाईकुण्ड गाउँपालिका'],
            ['2632', 2035, 'Kalika Rular municipality', 'कालिका गाउँपालिका'],
            ['2630', 2035, 'Aautirgaya Rular municipality', 'उतरगया गाउँपालिका'],
            ['2640', 2035, 'Parbatikundha rular municipality', 'पार्बतीकुन्ड गाउँपालिका'],
            ['2671', 2036, 'Sureygadhi rular municipality', 'सुर्यगढी गाउँपालिका'],
            ['2666', 2036, 'Shivapuri rular municipality', 'शिबपुरी गाउँपालिका'],
            ['2656', 2036, 'dupcheshowar rular municipality', 'दुप्चेश्रर गाउँपालिका'],
            ['2650', 2036, 'Tadi rular municipality', 'तादी गाउँपालिका'],
            ['2648', 2036, 'Kispanga rular municipality', 'किस्पाङ गाउँपालिका'],
            ['2646', 2036, 'kakani rular municipality', 'ककनी गाउँँपालिका'],
            ['2643', 2036, 'Bidhur  Municipaltiy', 'बिदुर नगरपालिका'],
            ['2653', 2036, 'Tarakeshowar rular municipality', 'तारकेश्वर गाउँपालिका'],
            ['2644', 2036, 'Belakotgadhi nagarpalika', 'बेलकोटगढी नगरपालिका'],
            ['2659', 2036, 'pansakanya rular municipality', 'पश्रकन्या गाउँपालिका'],
            ['2661', 2036, 'Likhu rular municipality', 'लिखु गाउँपालिका'],
            ['2663', 2036, 'Meghanga rular municipality', 'मेघाङ गाउँपालिका'],
            ['2700', 2037, 'Jawalamukhi rular municipality', 'ज्बालामुखी गाउँपालिका'],
            ['2674', 2037, 'Dhunibeshi nagarpalika', 'धुनीर्बेशी नगरपालिका'],
            ['2679', 2037, 'Nilkandha nagarpalika', 'निलकण्ठ नगरपालिका'],
            ['2682', 2037, 'khaniyabasa Rular municipality', 'खनियाबास गाउँपालिका'],
            ['2686', 2037, 'Gajuri rular municipality', 'गजुरी गाउँपालिका'],
            ['2691', 2037, 'Galchhi rular municipality', 'गल्छी गाउँपालिका'],
            ['2697', 2037, 'Gangajamuna rular municipality', 'गंगाजमुना गाउँपालिका'],
            ['2703', 2037, 'Thakre rular municipality', 'थाक्र्रे गाउँपालिका'],
            ['2708', 2037, 'Netrabati Rular Municipality', 'नेत्राबती गाउँपालीका'],
            ['2711', 2037, 'Benighat roranga rular municipality', 'बेनीघाट रोराङ गाँउपालिका'],
            ['2716', 2037, 'Ruvi vally Rular Municipality', 'रूवी भ्याली गाँउपालिका'],
            ['2718', 2037, 'Siddhalek Rular Municipality', 'सिद्धलेक गाँउपालिका'],
            ['2723', 2037, 'Tripurasundhari Rular Municipality', 'त्रिपुरासुन्दरी गाउँपालिका'],
            ['2736', 2038, 'Khairahani nagarpalika', 'खैरहनी नगरपालिका'],
            ['2738', 2038, 'Madhi  Municipaltiy', 'माडी नगरपालिका'],
            ['2741', 2038, 'Ratnagar nagarpalika', 'रत्रनगर नगरपालिका'],
            ['2743', 2038, 'Rapti nagarpalika', 'राप्ती नगरपालिका'],
            ['2745', 2038, 'Icchakamana rular municipality', 'इच्छाकामना गाउँपालीका'],
            ['2735', 2038, 'Kalika Municipality', 'कालिका नगरपालिका'],
            ['2732', 2038, 'Bharatpur  Metropolitian', 'भरतपुर महानगरपालिका'],
            ['2695', 2039, 'Bakaiya Rular Muncipality', 'बकैया गाउँपालिका'],
            ['2688', 2039, 'Kailash Rular muncipality', 'कैलास गाउँपालिका'],
            ['2676', 2039, 'Hetauda Submetropolitain', 'हेटौडा उप महानगरपालीका'],
            ['2698', 2039, 'Bagmati Rular Muncipality', 'वाग्मती गाउँपालिका'],
            ['2684', 2039, 'Indrasarobar Rularmuncipalaty', 'इन्द्रसरोवर गाउँपालिका'],
            ['2707', 2039, 'Manahari Rular Muncipality', 'मनहरी गाउँपालीका'],
            ['2705', 2039, 'Makwanpurgadhi Rular Muncipality', 'मकवानपुरगढी गाउँपालीका'],
            ['2680', 2039, 'Taha muncipality', 'थाहा नगरपालीका'],
            ['2710', 2039, 'RakshiRang Rular Muncipality', 'राक्सिराङ गाउपालीका'],
            ['2702', 2039, 'Bhimphadi Rular Muncipality', 'भिमफेदी गाउँपालिका'],
            ['2593', 2040, 'Suryabinaya Municipality', 'सुर्यबिनायक नगरपालिका'],
            ['2592', 2040, 'Madhyapur Thimi Municipality', 'मध्यपुर थिमी नगरपालिका'],
            ['2588', 2040, 'Chagunarayan Municipality', 'चाँगुनारायण नगरपालिका'],
            ['2590', 2040, 'Bhaktapur Munucipalty', 'भक्तपुर नगरपालिका'],
            ['2586', 2041, 'Mahanala Rural Municipality', 'महाङाल गाउँपालिका'],
            ['2581', 2041, 'Mahalaxmi Municipality', 'महालक्ष्मी नगरपालिका'],
            ['2582', 2041, 'Konjyoshoma Rural Municipality', 'कोन्ज्योसोम गाउँपालिका'],
            ['2580', 2041, 'Godhabari Municipality', 'गोदाबरी नगरपालिका'],
            ['2579', 2041, 'Lalitapur Metropolian', 'ललितपुर महानगरपालिका'],
            ['2583', 2041, 'Bagmati Rural Municipality', 'बाग्मती गाउँपालिका'],
            ['2603', 2042, 'Tokha Municipality', 'टोखा नगरपालिका'],
            ['2602', 2042, 'Chadragiri Municipality', 'चन्द्रागिरी नगरपालिका'],
            ['2627', 2042, 'Sanrapur Municipality', 'शंखरापुर नगरपालिका'],
            ['2601', 2042, 'Gokanaswor Municipality', 'गोकर्णेश्वर नगरपालिका'],
            ['2606', 2042, 'Nagarjun Municipality', 'नागार्जुन नगरपालिका'],
            ['2597', 2042, 'Kagesowari Manohara Municipality', 'कागेश्वरी मनोहरा नगरपालिका'],
            ['2625', 2042, 'Budhanilakantha Municipality', 'बुढानिलकण्ठ नगरपालिका'],
            ['2600', 2042, 'Kritipur Municipality', 'कीर्तिपुर नगरपालिका'],
            ['2604', 2042, 'Tarakeshowar Municipality', 'तारकेश्वर नगरपालिका'],
            ['2595', 2042, 'Kathmandu Metropolian', 'काठमाडौं महानगरपालिका'],
            ['2605', 2042, 'Dakshinkali Municipality', 'दक्षिणकाली नगरपालिका'],
            ['2775', 2043, 'Sahid lakhan rular municipality', 'शहिद लखन गाउँपालिका'],
            ['2749', 2043, 'Ghorakha nagarpalika', 'गोरखा नगरपालिका'],
            ['2751', 2043, 'Palungatar  nagarpalika', 'पालुङटार नगरपालिका'],
            ['2754', 2043, 'Siranchowok rular municipality', 'सिरानचोक गाउँपालीका'],
            ['2756', 2043, 'Arughat rular  municipality', 'आरूघाट गाउँपालीका'],
            ['2755', 2043, 'Aajirkot rular  municipality', 'अजिरकोट गाउँपालीका'],
            ['2753', 2043, 'Shulikot Rural Municipaltiy', 'सुलीकोट गाउँपालीका'],
            ['2757', 2043, 'Gandaki rular municipality', 'गण्डकी गाउँपालीका'],
            ['2759', 2043, 'Dhache rular municipality', 'धार्चे गाउँपालीका'],
            ['2774', 2043, 'Bhisena rular municipality', 'भिमसेन गाउँपालीका'],
            ['2780', 2044, 'Sundarbazzar nagarpalika', 'सुन्दरबजार नगरपालिका'],
            ['2779', 2044, 'Rainas nagarpalika', 'राईनास नगरपालिका'],
            ['2777', 2044, 'Beshisahara nagarpalika', 'बेसीशहर नगरपालिका'],
            ['2778', 2044, 'Madhenepali Municipaltiy', 'मध्यनेपाल नगरपालिका'],
            ['2789', 2044, 'Marsand rular municipality', 'मस्र्याङदी गाउँपालीका'],
            ['2786', 2044, 'Dodri rular municipality', 'दोर्दी गाँउपालिका'],
            ['2781', 2044, 'Kabholasothar  rular municipality', 'कव्होलासोथार गाउँपालीका'],
            ['2782', 2044, 'dudhapokhari rular municipality', 'दुधपोखरी गाउँपालीका'],
            ['2825', 2045, 'maygde rural municipality', 'म्याग्दे गाउँपालीका'],
            ['2794', 2045, 'Bhimad municipality', 'भिमाद नगरपालिका'],
            ['2823', 2045, 'Debaghat rurar municipality', 'देबघाट गाउँपालीका'],
            ['2829', 2045, 'Bandhipur rural municipality', 'बन्दिपुर गाउँपालीका'],
            ['2820', 2045, 'Ghiringa Rural Municipality', 'घिरिङ गाउँपालीका'],
            ['2798', 2045, 'Suklagandaki municipality', 'सुक्लागण्डकी नगरपालिका'],
            ['2796', 2045, 'Payasa municipality', 'व्यास नगरपालिका'],
            ['2793', 2045, 'Bhanu municipality', 'भानु नगरपालिका'],
            ['2816', 2045, 'Shisenga rural municipality', 'ऋषिङ गाउँपालीका'],
            ['2800', 2045, 'Aabukhaireni Rural  Municipality', 'आँबुखैरेनी गाउँपालीका'],
            ['2965', 2046, 'Rupa Rural Muncipality', 'रूपा गाउँपालीका'],
            ['2959', 2046, 'Machapuche Rural Muncipality', 'माछापुच्छे गाउँपालीका'],
            ['2962', 2046, 'Madi Rural Muncipality', 'मादी गाउँपालीका'],
            ['2955', 2046, 'Pokhara Lekhnath mertopolitiancity', 'पोखरा लेखनाथ महानगरपालीका'],
            ['2957', 2046, 'Annapurna Rural Muncipality', 'अन्नपुर्ण गाउँपालीका'],
            ['2978', 2047, 'Narafu Rural Muncipality', 'नारफु गाउँपालीका'],
            ['2999', 2047, 'Nasong Rural Muncipality', 'नासोङ गाउँपालीका'],
            ['3003', 2047, 'Nesang Rural Muncipality', 'नेस्याङ गाउँपालीका'],
            ['2976', 2047, 'Chame Rural Muncipality', 'चामे गाउँपालीका'],
            ['3015', 2048, 'Lemthang Rural Muncipality', 'लेमन्थाङ गाउँपालीका'],
            ['3017', 2048, 'baragau mukti rural municipality', 'बाह्रगाँउ मुत्तिक्षेत्र गाउँपालिका'],
            ['3010', 2048, 'Thasang Rural Muncipalicity', 'थासाङ गाउँपालीका'],
            ['3008', 2048, 'Gharpaghang Rural Municipaltiy', 'घरपझोङ गाँउपालिका'],
            ['3013', 2048, 'Dalome rural municipality', 'दालोमे गाउँपालिका'],
            ['2984', 2049, 'Falebash Municipality', 'फलेवास नगरपालिका'],
            ['2998', 2049, 'Bihadi Rular Municipality', 'विहादी गाउँपालीका'],
            ['2995', 2049, 'Mahashila Rular Municipality', 'महाशिला गाउँपालीका'],
            ['2987', 2049, 'Paiyu Rular Municipality', 'पैंयू गाउँपालीका'],
            ['2996', 2049, 'Modi Rular Municipality', 'मोदी गाउँपालीका'],
            ['2985', 2049, 'Jaljala Rular Municipality', 'जलजला गाउँपालीका'],
            ['2983', 2049, 'Kushma Municipality', 'कुश्मा नगरपालिका'],
            ['2856', 2050, 'Galayanga municipality', 'गल्याङ नगरपालिका'],
            ['2963', 2050, 'Walinga municipality', 'बालिङ नगरपालिका'],
            ['2881', 2050, 'Virakot municipality', 'भिरकोट नगरपालिका'],
            ['2877', 2050, 'Putalibazzar municipality', 'पुतलीबजार नगरपालिका'],
            ['2874', 2050, 'chapakot municipality', 'चापाकोट नगरपालिका'],
            ['3000', 2050, 'Marinasa Rular Municipality', 'हरिनास गाउँपालिका'],
            ['2997', 2050, 'Biruba rular municipality', 'बिरूबा गाउँपालिका'],
            ['2994', 2050, 'fedikhola rular municipality', 'फेदीखोला गाउँपालिका'],
            ['2986', 2050, 'kaligandaki rular municipality', 'कालीगण्डकी गाउँपालिका'],
            ['2977', 2050, 'Aadikhola rular municipalty', 'आधिखोला गाउँपालिका'],
            ['2974', 2050, 'Aajunchaupari rular municipality', 'अजुर्नचौपारी गाउँपालिका'],
            ['2979', 2051, 'Dhaulagiri rular municipality', 'धवलागिरी गाउँपालीका'],
            ['2966', 2051, 'Beni municipality', 'बेनी नगरपालिका'],
            ['2975', 2051, 'Annapurna rular municipality', 'अन्नपुर्ण गाउँपालीका'],
            ['2982', 2051, 'Raghu rular municipality', 'रघु गंगा गाउँपालीका'],
            ['2981', 2051, 'Malika rular municipality', 'मालिका गाउंपाकिला'],
            ['2980', 2051, 'Mangala Rular municipality', 'मंगला गाउँपालीका'],
            ['3020', 2052, 'Tamankhola Rular  Municipality', 'तमानखोला गाउँपालीका'],
            ['3012', 2052, 'Dhorpatan Municipality', 'ढोरपाटन नगरपालिका'],
            ['3005', 2052, 'Baglung Municipality', 'बागलुङ नगरपालिका'],
            ['3007', 2052, 'Galkota Municipality', 'गल्कोटा नगरपाकिला'],
            ['3011', 2052, 'Jaimini Municipality', 'जैमिनी नगरपालिका'],
            ['3022', 2052, 'Tarakhola Rular Municipality', 'ताराखोला गाउँपालीका'],
            ['3024', 2052, 'Nishikhola Rular Municipality', 'निसीखोला गाउँपालीका'],
            ['3026', 2052, 'Badigad Rular Municipality', 'वडिगाड गाउँपालीका'],
            ['3016', 2052, 'wareng Rular Minicipality', 'वरेङ गाउँपालीका'],
            ['3019', 2052, 'Kathekhola Rular Minicipality', 'काठेखोला गाउँपालीका'],
            ['2537', 2053, 'Bulintar Rural Municipaltiy', 'बुलीङटार गाउँपालिका'],
            ['2535', 2053, 'bundikali rural municipality', 'बुङ्दीकाली गाउँपालिका'],
            ['2538', 2053, 'Binayi Tribeni Rural municipality', 'विनयी-त्रिवेणी गाउँपालिका'],
            ['2477', 2053, 'Madyabindu Municipality', 'मध्यविन्दु नगरपालिका'],
            ['2473', 2053, 'Kabasoti Municipality', 'कावासोती नगरपालिका'],
            ['2475', 2053, 'Devchuli Municipality', 'देबचुली नगरपालिका'],
            ['2474', 2053, 'Gaidakot Municipality', 'गैडाकोट नगरपालिका'],
            ['2540', 2053, 'Hupsekot Rural Municipality', 'हुप्सेकोट गाउँपालिका'],
            ['2476', 2054, 'Bardaghat Municipality', 'बर्दघाट नगरपालिका'],
            ['2532', 2054, 'palhinnadan rural municipality', 'पाल्हीनन्दन गाउँपालिका'],
            ['2539', 2054, 'Sarabal Rural Municipaltiy', 'सरावल गाउँपालिका'],
            ['2480', 2054, 'Tribenisusta Municipality', 'त्रिवेणीसुस्ता नगरपालिका'],
            ['2534', 2054, 'Partappur rural municipality', 'प्रतापपुर गाउँपालिका'],
            ['2478', 2054, 'Ramgram Municipality', 'रामग्राम नगरपालिका'],
            ['2479', 2054, 'Sunabol Municipality', 'सुनवल नगरपालिका'],
            ['2489', 2055, 'Omsatiya Rural Municipality', 'ओमसतिया गाउँपालिका'],
            ['2317', 2055, 'Butwal SMC', 'बुटवल उपमहानगरपालिका'],
            ['2493', 2055, 'Suddhodhan Rural Municipality', 'शुद्धोधन गाउँपालिका'],
            ['2464', 2055, 'Gaidhawa Rural Municipality', 'गैडहवा गाउँपालिका'],
            ['2485', 2055, 'Kanchan Rural Municipality', 'कन्चन गाउँपालिका'],
            ['2486', 2055, 'Kotahimai Rural Muncipal', 'कोटहीमाई गाउँपालिका'],
            ['2487', 2055, 'Marchawari Rural Municipality', 'मर्चवारी गाउँपालिका'],
            ['2488', 2055, 'Mayadevi Rural Municipality', 'मायादेवी गाउँपालिका'],
            ['2490', 2055, 'Rohini Rural Municipality', 'रोहिणी गाउँपालिका'],
            ['2491', 2055, 'Sammarimari Rural Municipality', 'सम्मरीमाई गाउँपालिका'],
            ['2492', 2055, 'Siyari Rural Municipality', 'सियारी गाउँपालिका'],
            ['2323', 2055, 'Devdaha Municipality', 'देवदह नगरपालिका'],
            ['2327', 2055, 'Lumbini Saskrit Municipality', 'लुम्बिनी सांस्कृतिक नगरपालिका'],
            ['2330', 2055, 'Sainamaina Municipality', 'सैनामैना नगरपालिका'],
            ['2365', 2055, 'Siddharthanagar Municipality', 'सिद्धार्थनगर नगरपालिका'],
            ['2366', 2055, 'Tilottama Municipality', 'तिलोत्तमा नगरपालिका'],
            ['2413', 2056, 'BANAGANGA MUNICIPALITY', 'बाणगंगा नगरपालिका'],
            ['2496', 2056, 'Shivaraj Municipality', 'शिवराज नगरपालिका'],
            ['2495', 2056, 'Buddhabhumi Municipality', 'बुद्धभुमी नगरपालिका'],
            ['2494', 2056, 'kapilvastu Municipality', 'कपिलवस्तु नगरपालिका'],
            ['2414', 2056, 'MAYADEVI RURAL MUNICIPALITY', 'मायादेवी गाउँपालिका'],
            ['2420', 2056, 'BIJAYANAGAR RURAL MUNICIPALITY', 'विजयनगर गाँउपालिका'],
            ['2419', 2056, 'SUDDHODHAN RURAL MUNICIPALITY', 'शुद्धोधन गाउँपालिका'],
            ['2416', 2056, 'YASHODHARA RURAL MUNICIPALITY', 'यसोधरा गाउँपालिका'],
            ['2409', 2056, 'KRISHNAGAR MUNICIPALITY', 'कृष्णनगर नगरपालिका'],
            ['2497', 2056, 'Maharajgunj Municipality', 'महाराजगंज नगरपालिका'],
            ['2460', 2057, 'Tansen Municipality', 'तानसेन नगरपालिका'],
            ['2462', 2057, 'Purbakhola Rural Municipality', 'पुर्वखोला गाउँपालिका'],
            ['2465', 2057, 'Mathagadhi Rural Municipality', 'माथागढी गाउँपालिका'],
            ['2469', 2057, 'Ribdikot Rural Municipality', 'रिब्दीकोट गाउँपालिका'],
            ['2463', 2057, 'Rambha Rural Municipality', 'रम्भा गाउँपालिका'],
            ['2471', 2057, 'Raina Rural Municipality', 'रैनादेवी गाउँपालिका'],
            ['2466', 2057, 'Tinau Rural Municipality', 'तिनाउ गाउँपालिका'],
            ['2455', 2057, 'RAMPUR MUNICIPALITY', 'रामपुर नगरपालिका'],
            ['2467', 2057, 'Bagnaskali Rural Municipality', 'बगनासकाली गाउँपालिका'],
            ['2461', 2057, 'Nisdi Rural Municipality', 'निस्दी गाउँपालिका'],
            ['2388', 2058, 'SITGANGA MUNICIPALITY', 'शितगंगा नगरपालिका'],
            ['2398', 2058, 'MALARANI RURAL MUNICIPALITY', 'मालारानी गाउँपालिका'],
            ['2385', 2058, 'SANDHIKHARKA MUNICIPALITY', 'सन्धीखर्क नगरपालिका'],
            ['2396', 2058, 'PANINI RURAL MUNICIPALITY', 'पाणिनी गाउँपालिका'],
            ['2392', 2058, 'BHUMIKASTHAN MUNICIPALITY', 'भुमीकास्थान नगरपालिका'],
            ['2394', 2058, 'CHHATRADEV RURAL MUNICIPALITY', 'छत्रदेव गाउँपालिका'],
            ['2435', 2059, 'SATYAWATI RURAL MUNICIPALITY', 'सत्यवती गाउँपालिका'],
            ['2452', 2059, 'MAALIKA RURAL MUNICIPALITY', 'मालिका गाउँपालिका'],
            ['2451', 2059, 'MADANE RURAL MUNICIPALITY', 'मदाने गाउँपालिका'],
            ['2423', 2059, 'MUSHIKOT MUNICIPALITY', 'मुसिकोट नगरपालिका'],
            ['2448', 2059, 'DHURKOT RURAL MUNICIPALITY', 'धुर्कोट गाउँपालिका'],
            ['2445', 2059, 'CHHATRAKOT RURAL MUNICIPALITY', 'छत्रकोट गाउँपालिका'],
            ['2442', 2059, 'RURU RURAL MUNICIPALITY', 'रूरू गाउँपालिका'],
            ['2438', 2059, 'CHANDRAKOT RURAL MUNICIPALITY', 'चन्द्रकोट गाउँपालिका'],
            ['2424', 2059, 'RESUNGA MUNICIPALITY', 'रेसुङ्गा नगरपालिका'],
            ['2432', 2059, 'GULMIDARBAR RURAL MUNICIPALITY', 'गुल्मीदरबार गाउँपालिका'],
            ['2428', 2059, 'KALIGANDAGI RURAL MUNICIPALITY', 'कालीगण्डकी गाउँपालिका'],
            ['2427', 2059, 'ESMA RURAL MUNICIPALITY', 'इस्मा गाउँपालिका'],
            ['2572', 2060, 'Bhume  Rural Municipality', 'भुमे गाउँपालिका'],
            ['2573', 2060, 'Sisne  Rural Municipality', 'सिस्ने गाउँपालिका'],
            ['2545', 2060, 'Musikot Municipality', 'मुसिकोट नगरपालिका'],
            ['2570', 2060, 'Putha utarganga Rural Municipality', 'पुथा उत्तरगंगा गाउँपालिका'],
            ['2360', 2061, 'SUBARNAWATI RURAL MUNICIPALITY', 'सुर्वणावती गाउँपालिका'],
            ['2347', 2061, 'Madi  Rural Municipality', 'माडी गाउँपालिका'],
            ['2345', 2061, 'Dhuekholi  Rural Municipality', 'दुईखोली गाउँपालिका'],
            ['2362', 2061, 'Thabang  Rural Municipality', 'थबाङ गाउँपालिका'],
            ['2358', 2061, 'SUNACHHAHARI RURAL MUNICIPALITY', 'सुनछहरी गाउँपालिका'],
            ['2342', 2061, 'Tribeni  Rural Municipality', 'त्रिवेणी गाउँपालिका'],
            ['2340', 2061, 'ROLPA MUNICIPALITY', 'रोल्पा नगरपालिका'],
            ['2355', 2061, 'Sukidaha  Rural Municipality', 'सुकिदह गाउँपालिका'],
            ['2352', 2061, 'Lungri  Rural Municipality', 'लुङग्री गाउँपालिका'],
            ['2350', 2061, 'RUNTIGADHI RURAL MUNICIPALITY', 'रून्टीगढी गाउँपालिका'],
            ['2318', 2062, 'Sorgadhawori Municipality', 'स्र्वगद्धारी नगरपालिका'],
            ['2325', 2062, 'Mandabi Rural Municipality', 'माण्डवी गाउँपालिका'],
            ['2324', 2062, 'GAUMUKHI RURAL MUNICIPALITY', 'गौमुखी गाउँपालिका'],
            ['2334', 2062, 'NAUBAHINI RURAL MUNICIPALITY', 'नौबहिनी गाउँपालिका'],
            ['2332', 2062, 'MALLARANI RURAL MUNICIPALITY', 'मल्लारानी गाउँपालिका'],
            ['2319', 2062, 'JHIMRUK RURAL MUNICIPALITY', 'भिमरूक गाउँपालिका'],
            ['2338', 2062, 'Yeraoti Rural Municipality', 'एेरावती गाउँपालिका'],
            ['2329', 2062, 'Sarumarani  Rural Municipality', 'सरूमारानी गाउँपालिका'],
            ['2314', 2062, 'Pyuthan Municipality', 'प्यूठान नगरपालिका'],
            ['2145', 2063, 'Ghorahi SMC', 'घोराही उप-महानगरपालिका'],
            ['2157', 2063, 'Dangisaran Rural Municipaltiy', 'दंगीशरण गाउँपालिका'],
            ['2160', 2063, 'Gadhawa Rural Municipaltiy', 'गढवा गाउँपालिका'],
            ['2166', 2063, 'Shantinagar Rural Municipaltiy', 'शान्तिनगर गाउँपालिका'],
            ['2139', 2063, 'Tulshipur SMC', 'तुल्सीपुर उप-महानगरपालिका'],
            ['2161', 2063, 'Rajpur Rural Municipaltiy', 'राजपुर गाउँपालिका'],
            ['2151', 2063, 'Lamhi Municipality', 'लमही नगरपालिका'],
            ['2167', 2063, 'Babai Rural Municipaltiy', 'बबई गाउँपालिका'],
            ['2163', 2063, 'Rapti Rural Municipaltiy', 'राप्ती गाउँपालिका'],
            ['2154', 2063, 'Banglachuli Rural Municipaltiy', 'बंगलाचुली गाउँपालिका'],
            ['2181', 2064, 'Duduwa  Rural Municipality', 'डुडुवा गाउँपालिका'],
            ['2180', 2064, 'Khajura  Rural Municipality', 'खजुरा गाउँपालिका'],
            ['2177', 2064, 'Baijanath  Rural Municipality', 'बैजनाथ गाउँपालिका'],
            ['2175', 2064, 'Raptisonari  Rural Municipality', 'राप्तीसोनारी गाउँपालिका'],
            ['2173', 2064, 'Narainapur  Rural Municipality', 'नरैनापुर गाउँपालिका'],
            ['2170', 2064, 'Nepalgunj SMC', 'नेपालगंज उप-महानगरपालिका'],
            ['2172', 2064, 'Kohalpur Municipality', 'कोहलपुर नगरपालिका'],
            ['2184', 2064, 'Janaki  Rural Municipality', 'जानकी गाउँपालिका'],
            ['2292', 2065, 'Barbardiya Municipality', 'बारबर्दिया नगरपालिका'],
            ['2293', 2065, 'MADHUBAN MUNICIPALITY', 'मधुवन नगरपालिका'],
            ['2298', 2065, 'Thakurbaba Municipality', 'ठाकुरबाबा नगरपालिका'],
            ['2291', 2065, 'BADHAIYATAL RURAL MUNICIPALITY', 'बढैयाताल गाउँपालिका'],
            ['2289', 2065, 'Guleriya Municipality', 'गुलेरिया नगरपालिका'],
            ['2301', 2065, 'BANSGADHI MUNICIPALITY', 'बाँसगढी नगरपालिका'],
            ['2295', 2065, 'RAJPUR MUNICIPALITY', 'राजापुर नगरपालिका'],
            ['2296', 2065, 'Geruya Rural Municipality', 'गेरूवा गाउँपालिका'],
            ['2574', 2066, 'Baphikot  Rural Municipality', 'बाँफिकोट गाउँपालिका'],
            ['2578', 2066, 'Sanibheri  Rural Municipality', 'सानीभेरी गाउँपालिका'],
            ['2568', 2066, 'Aathabiskot Municipality', 'आठबिसकोट नगरपालिका'],
            ['2547', 2066, 'Churjahari  Municipality', 'चौरजहारी नगरपालिका'],
            ['2576', 2066, 'Tribeni  Rural Municipality', 'त्रिवेणी गाउँपालिका'],
            ['3027', 2067, 'Sharadha municipality', 'सारदा नगरपालिका'],
            ['3037', 2067, 'Kumakhamalika  Rural Municipality', 'कुमाखमालिका गाउँपालिका'],
            ['3036', 2067, 'Dhorchur  Rural Municipality', 'ढोरचौर गाउँपालिका'],
            ['3035', 2067, 'Chatredhari  Rural Municipality', 'छत्रेधरी गाउँपालिका'],
            ['3034', 2067, 'Kapurkot  Rural Municipality', 'कपुरकोट गाउँपालिका'],
            ['3031', 2067, 'Tribeni Rural Muncipality', 'त्रिवेणी गाउँपालीका'],
            ['3030', 2067, 'Kalimati Rural Muncipality', 'कालीमाटी गाउँपालीका'],
            ['3028', 2067, 'Bagchaur Muncipality', 'बागचौर नगरपालीका'],
            ['3032', 2067, 'Bangad kupende Municipality', 'बनगाड कुपेण्डे नगरपालिका'],
            ['3054', 2067, 'Darma  Rural Municipality', 'दार्मा गाउँपालिका'],
            ['2906', 2068, 'Kaeke  Rural Municipality', 'काईके गाउँपालिका'],
            ['2895', 2068, 'Thulibheri Municipality', 'ठुलीभेरी नगरपालिका'],
            ['2896', 2068, 'Tripurasundari Muncipality', 'त्रिपुरासुन्दरी नगरपालिका'],
            ['2915', 2068, 'Charka tanson  Rural Municipality', 'छार्का ताङसोङ गाउँपालिका'],
            ['2902', 2068, 'Jagdulla Rural Municipality', 'जगदुल्ला गाउँपालिका'],
            ['2901', 2068, 'She phoksundo  Rural Municipality', 'शे फोक्सुण्डो गाउँपालिका'],
            ['2899', 2068, 'Dulpo duddha  Rural Municipality', 'डोल्पो वुद्ध गाउँपालिका'],
            ['2904', 2068, 'Mudkecula  Rural Municipality', 'मुडकेचुला गाउँपालिका'],
            ['2920', 2069, 'Kankasundari Rural Municipality', 'कनकासुन्दरी गाउँपालिका'],
            ['2918', 2069, 'Candannatha Municipality', 'चन्दननाथ नगरपालिका'],
            ['2927', 2069, 'Patarasi  Rural Municipality', 'पातारासी गाउँपालिका'],
            ['2926', 2069, 'Tatopani  Rural Municipality', 'तातोपानी गाउँपालिका'],
            ['2925', 2069, 'Guthicaur  Rural Municipality', 'गुठिचौर गाउँपालिका'],
            ['2924', 2069, 'Tila  Rural Municipality', 'तिला गाउँपालिका'],
            ['2923', 2069, 'Hima  Rural Municipality', 'हिमा गाउँपालिका'],
            ['2921', 2069, 'Sreja  Rural Municipality', 'र्सिजा गाउँपालिका'],
            ['2988', 2070, 'Chayanatha rara Municipality', 'छायाँनाथ रारा नगरपालिका'],
            ['3001', 2070, 'Mugumakamarog  Rural Municipality', 'मुगुमकार्मार्रोग गाउँपालिका'],
            ['3002', 2070, 'Soru  Rural Municipality', 'सोरू गाउँपालिका'],
            ['3004', 2070, 'Khatyad  Rural Municipality', 'खत्याड गाउँपालिका'],
            ['3021', 2071, 'Carkheli  Rural Municipality', 'च'],
            ['3006', 2071, 'Simkot  Rural Municipality', 'सिमकोट गाउँपालिका'],
            ['3014', 2071, 'Khapunatha  Rural Municipality', 'खार्पुनाथ गाउँपालिका'],
            ['3009', 2071, 'Namkha  Rural Municipality', 'नाम्खा गाउँपालिका'],
            ['3018', 2071, 'Sarkegad  Rural Municipality', 'सर्केगाड गाउँपालिका'],
            ['3023', 2071, 'Aadanculi  Rural Municipality', 'अदानचुली गाउँपालिका'],
            ['3025', 2071, 'Tajakot  Rural Municipality', 'ताँजाकोट गाउँपालिका'],
            ['2961', 2072, 'Mahabai  Rural Municipality', 'महावै गाउँपालिका'],
            ['2958', 2072, 'Narharinath  Rural Municipality', 'नरहरिनाथ गाउँपालिका'],
            ['2956', 2072, 'Satri tribeni  Rural Municipality', 'साञी ञिवेणी गाउँपालिका'],
            ['2954', 2072, 'Pachaljarana  Rural Municipality', 'पचालझरना गाउँपालिका'],
            ['2934', 2072, 'Khadachakra Municipality', 'खाँडाचक्र नगरपालिका'],
            ['2936', 2072, 'Tilagufa Municipality', 'तिलागुफा नगरपालिका'],
            ['2935', 2072, 'Raskot Municipality', 'रास्कोट नगरपालिका'],
            ['2964', 2072, 'Palata  Rural Municipality', 'पलाता गाउँपालिका'],
            ['2960', 2072, 'Kalika  Rural Municipality', 'कालिका गाउँपालिका'],
            ['2887', 2073, 'Junicade  Rural Municipality', 'जुनीचाँदे गाउँपालिका'],
            ['2885', 2073, 'Tribeni nalgad Municipality', 'त्रिवेणी नलगाड नगरपालिका'],
            ['2884', 2073, 'Chedagad Municipality', 'छेडागाड नगरपालिका'],
            ['2883', 2073, 'Bheri Municipality', 'भेरी नगरपालिका'],
            ['2886', 2073, 'Kuse  Rural Municipality', 'कुसे गाउँपालिका'],
            ['2890', 2073, 'Shibalaya  Rural Municipality', 'शिवालय गाउँपालिका'],
            ['2888', 2073, 'Barekot  Rural Municipality', 'बारेकोट गाउँपालिका'],
            ['2880', 2074, 'Bhirabi  Rural Municipality', 'भैरवी गाउँपालिका'],
            ['2854', 2074, 'Bhagwatimae  Rural Municipality', 'भगवतीमाई गाउँपालिका'],
            ['2855', 2074, 'Guras  Rural Municipality', 'गुरास गाउँपालिका'],
            ['2876', 2074, 'Dungedhar  Rural Municipality', 'डुङ्गेधर गाउँपालिका'],
            ['2878', 2074, 'Naumule  Rural Municipality', 'नैमुले गाउँपालिका'],
            ['2879', 2074, 'Mahabu  Rural Municipality', 'महाबु गाउँपालिका'],
            ['2882', 2074, 'Thatikadha  Rural Municipality', 'ठाँटीकाँध गाउँपालिका'],
            ['2831', 2074, 'Narayana Municipality', 'नारायण नगरपालिका'],
            ['2832', 2074, 'Dullu Municipality', 'दुल्लु नगरपालिका'],
            ['2833', 2074, 'Camunda bindrasaini Municipality', 'चामुण्डा विन्द्रासैनी नगरपालिका'],
            ['2834', 2074, 'Aathabis Municipality', 'आठबिस नगरपालिका'],
            ['2822', 2075, 'Barahatal  Rural Municipality', 'बराहताल गाउँपालिका'],
            ['2788', 2075, 'Gurbhakot Municipality', 'गुर्भाकोट नगरपालिका'],
            ['2814', 2075, 'Panshapuri Municipality', 'पश्रपुरी नगरपालिका'],
            ['2817', 2075, 'Lekbeshi Municipality', 'लेकबेशी नगरपालिका'],
            ['2819', 2075, 'Chukune Rural Municipality', 'चौकुने गाउँपालिका'],
            ['2830', 2075, 'Simta  Rural Municipality', 'सिम्ता गाउँपालिका'],
            ['2827', 2075, 'Chingad  Rural Municipality', 'चिङ्गाड गाउँपालिका'],
            ['2784', 2075, 'Berendranagar Municipality', 'वीरेन्द्रनगर नगरपालिका'],
            ['2785', 2075, 'Bheriganga Municipality', 'भेरीगंगा नगरपालिका'],
            ['2587', 2076, 'Budignga Municipality', 'बुढीगंगा नगरपालिका'],
            ['2594', 2076, 'PANDAV GUPHA RURAL MUNICIPALITY', 'पाण्डव गुफा गाउँपालिका'],
            ['2596', 2076, 'SWAMIKARTIK RURAL MUNICIPALITY', 'स्वामीकार्त्तिक गाउँपालिका'],
            ['2598', 2076, 'CHHEDEDAHARURAL MUNICIPALITY', 'छेडेदह गाउँपालिका'],
            ['2599', 2076, 'HIMALI RURAL MUNICIPALITY', 'हिमाली गाउँपालिका'],
            ['2591', 2076, 'Gaumul Rural Municipality', 'गौमुल गाउँपालिका'],
            ['2589', 2076, 'Budhinanda Munucipality', 'बुढीनन्दा नगरपालिका'],
            ['2584', 2076, 'Badimalika Municipality', 'बडिमालीका नगरपालिका'],
            ['2585', 2076, 'Tribeni Municipality', 'त्रिवेणी नगरपालिका'],
            ['2637', 2077, 'Chabispathivera Rural Municipality', 'छबिसपाथीभेरा गाउँपालिका'],
            ['2639', 2077, 'Durgathali Rural Municipality', 'दुर्गाथली गाउँपालिका'],
            ['2641', 2077, 'Kedarsyun Rural Municipality', 'केदारस्युँ गाउँपालिका'],
            ['2642', 2077, 'Kada Rural Municipality', 'काँडा गाउँपालिका'],
            ['2626', 2077, 'BUNGAL MUNICIPALITY', 'बुंगल नगरपालिका'],
            ['2607', 2077, 'JAYAPRITHVI MUNICIPALITY', 'जयपृथ्वी नगरपालिका'],
            ['2631', 2077, 'KHAPTADCHHATRA Rural Municipaltiy', 'खप्तडछात्रा गाउँपालिका'],
            ['2629', 2077, 'MASTA RURAL MUNICIPALITY', 'मष्टा गाउँपालिका'],
            ['2628', 2077, 'TALKOT RURAL MUNICIPALITY', 'तलकोट गाउँपालिका'],
            ['2633', 2077, 'Thalara Rural Municipality', 'थलारा गाँउपालिका'],
            ['2634', 2077, 'Bitthadachir Rural Municipality', 'वित्थडचिर गाउँपालिका'],
            ['2636', 2077, 'Surma Rural Municipality', 'सूर्मा गाउँपालिका'],
            ['2665', 2078, 'Purbichuki Rural Municipality', 'पूर्वीचौकी गाउँपालिका'],
            ['2669', 2078, 'Sayal Rural Municipality', 'सायल गाउँपालिका'],
            ['2662', 2078, 'Dipayal silgadi Municipality', 'दिपायल सिलगढी नगरपालिका'],
            ['2673', 2078, 'Bogatan Rural Municipality', 'बोगटान गाउँपालिका'],
            ['2664', 2078, 'Shikhar Municipality', 'शिखर नगरपालिका'],
            ['2668', 2078, 'Jorayal Rural Municipality', 'जोरायल गाउँपालिका'],
            ['2672', 2078, 'K.I.C Rural Municipality', 'कें.आई.सी गाउँपालिका'],
            ['2667', 2078, 'Badikedar Rural Municipality', 'बडिकेदार गाउँपालिका'],
            ['2670', 2078, 'Aadarsha Rural Municipality', 'आर्दश गाउँपालिका'],
            ['2647', 2079, 'Kamalbazar Municipality', 'कमलबजार नगरपालिका'],
            ['2658', 2079, 'Dhakari Rural Municipality', 'ढकारी गाउँपालिका'],
            ['2645', 2079, 'Mangalsen  Municipality', 'मंगलसेन नगरपालिका'],
            ['2657', 2079, 'Ramaroshan Rural Municipality', 'रामारोशन गाउँपालिका'],
            ['2649', 2079, 'Saphebazar Municipality', 'साँफेबजार नगरपालिका'],
            ['2651', 2079, 'Panchadebal Binayak Municipality', 'पंचदेवल विनायक नगरपालिका'],
            ['2660', 2079, 'Turmakhad Rural Municipality', 'तुर्माखाँद गाउँपालिका'],
            ['2652', 2079, 'Churpati Rural Municipality', 'चौरपाटी गाउँपालिका'],
            ['2654', 2079, 'Mellekha Rural Municipality', 'मेल्लेख गाउँपालिका'],
            ['2655', 2079, 'Batrigadi Jaygadi Rural Municipality', 'बात्रीगढी जयगढ गाउँपालिका'],
            ['2721', 2080, 'Malikarjun  Rural Municipality', 'मालिकार्जुन गाउँपालिका'],
            ['2719', 2080, 'Mahakali Municipality', 'महाकाली नगरपालिका'],
            ['2720', 2080, 'Shailyashikhar Municipality', 'शैल्यशिखर नगरपालिका'],
            ['2733', 2080, 'Byas  Rural Municipality', 'ब्याँस गाउँपालिका'],
            ['2731', 2080, 'Lekam  Rural Municipality', 'लेकम गाउँपालिका'],
            ['2729', 2080, 'Marma  Rural Municipality', 'मार्मा गाउँपालिका'],
            ['2727', 2080, 'Naugad  Rural Municipality', 'नौगाड गाउँपालिका'],
            ['2726', 2080, 'Duhu  Rural Municipality', 'दुहुँ गाउँपालिका'],
            ['2724', 2080, 'Apihimal  Rural Municipality', 'अपिहिमाल गाउँपालिका'],
            ['2519', 2081, 'Dashrathchand Muncipality', 'दशरथचन्द नगरपालिका'],
            ['2525', 2081, 'Sigas Rural Municipality', 'सिगास गाउँपालिका'],
            ['2528', 2081, 'Pancheshwor Rural Municipality', 'पन्चेश्वर गाउँपालिका'],
            ['2526', 2081, 'Shivanath Rural Municipality', 'शिवनाथ गाउँपालिका'],
            ['2521', 2081, 'Melauli Municipality', 'मेलौली नगरपालिका'],
            ['2530', 2081, 'Dilasaini Rural Municipality', 'डिलासैनी गाउँपालिका'],
            ['2529', 2081, 'Dogadakedar Rural Municipality', 'दोगडाकेदार गाउँपालिका'],
            ['2520', 2081, 'Patan Municipaltiy', 'पाटन नगरपालिका'],
            ['2524', 2081, 'Sunarya Rural Municipality', 'सुर्नया गाउँपालिका'],
            ['2523', 2081, 'Purchaudi Muncipality', 'पुर्चौडी नगरपालिका'],
            ['2512', 2082, 'Bhageswar Rural Municipality', 'भागेश्वर गाउँपालिका'],
            ['2513', 2082, 'Nawadurga Rural Municipality', 'नवदुर्गा गाउँपालिका'],
            ['2515', 2082, 'Ajayameru Rural Municipality', 'अजयमेरू गाउँपालिका'],
            ['2517', 2082, 'Ganyapdhura Rural Municipality', 'गन्यापधुरा गाउँपालिका'],
            ['2509', 2082, 'Amargadhi Municipality', 'अमरगढी नगरपालिका'],
            ['2510', 2082, 'Parshuram Municipaltiy', 'परशुराम नगरपालिका'],
            ['2511', 2082, 'Aalital Rural Municipaltiy', 'आलिताल गाउँपालिका'],
            ['2699', 2083, 'Bhimdatta Municipality', 'भीमदत्त नगरपालिका'],
            ['2712', 2083, 'Belauri Municipality', 'बेेलौरी नगरपालिका'],
            ['2706', 2083, 'Mahakali Municipality', 'माहाकाली नगरपालिका'],
            ['2713', 2083, 'Krishnapur Municipality', 'कृष्णपुर नगरपालिका'],
            ['2704', 2083, 'Bedkot Municipality', 'बेदकोट नगरपालिका'],
            ['2701', 2083, 'Punarbas Municipality', 'पुनर्वास नगरपालिका'],
            ['2709', 2083, 'Shuklaphat Municipality', 'शुक्ला‌फाँटा नगरपालिका'],
            ['2714', 2083, 'Beldandi  Rural Municipality', 'बेलडाँडी गाउँपालिका'],
            ['2717', 2083, 'Laljhadi  Rural Municipality', 'लालझाडी गाउँपालिका'],
            ['2687', 2084, 'Gauriganga Municipality', 'गौरीगंगा नगरपालीका'],
            ['2683', 2084, 'Bhajani Municipality', 'भजनी नगरपालिका'],
            ['2685', 2084, 'Godawari Municipality', 'गोदावरी नगरपालिका'],
            ['2678', 2084, 'Ghodaghodi Municipality', 'घोडाघोडी नगरपालिका'],
            ['2681', 2084, 'Lamkichuha Municipality', 'लम्किचुहा नगरपालिका'],
            ['2689', 2084, 'Janaki  Rural Municipality', 'जानकी गाउँपालिका'],
            ['2690', 2084, 'Bardagoriya  Rural Municipality', 'बर्दगोरिया गाउँपालिका'],
            ['2692', 2084, 'Mohanyal  Rural Municipality', 'मोहन्याल गाउँपालिका'],
            ['2693', 2084, 'Kailali  Rural Municipality', 'कैलाली गाउँपालिका'],
            ['2694', 2084, 'Josipur  Rural Municipality', 'जोशीपुर गाउँपालिका'],
            ['2677', 2084, 'Tikapur   Municipality', 'टिकापुर नगरपालिका'],
            ['2696', 2084, 'Chure  Rural Municipality', 'चुरे गाउँपालिका'],
            ['2675', 2084, 'Dhangadi SMC', 'धनगढी उपमहानगरपालिका'],
        ];

            foreach ($localLevels as $item) {
                $transformedData[] = [
                    'code' => $item[0],
                    'district_id'=>$item[1],
                    'name' => $item[2],
                    'name_np' => $item[3]
                ];
            }


        foreach ($transformedData as $localLevel) {
            LocalLevel::create($localLevel);
        }
    }
}
